import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './dist/sass/main.scss'
import Image from 'next/image'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className="header grid grid--col80">
        <div className="block__inner flex_ flex_space">
            <div className="header__logo">
               <Link href="/">
                    <Image src={require('./dist/webImages/logo.png')} alt="" />
                </Link>
            </div>

            <div className="header__right flex_ flex_space">
                <Link href="" className="nav_toggle">
                    <i className="fa-solid fa-bars"></i>
                </Link>
                <nav className="header__right--menu">
                    <a className="closeNav"> <i className="fa-solid fa-xmark"></i></a>
                    <ul className="header__right--menu-m list list-inline">
                        <li className="list__item">
                            <div className="sideMenuinner flex_ flex_space">
                                <Link href="/" className="active">Home</Link>
                                <Link href="" className="dropdown"><i className="fa-solid fa-chevron-down"></i></Link>
                            </div>
                        </li>
                        <li className="list__item">
                            <div className="sideMenuinner flex_ flex_space">
                                <Link href="/about">About</Link>
                                <Link href="" className="dropdown"><i className="fa-solid fa-chevron-down"></i></Link>
                            </div>
                        </li>
                        <li className="list__item">

                            <div className="sideMenuinner flex_ flex_space">
                                <Link href="">Services</Link>
                                <Link href="" className="dropdown"><i className="fa-solid fa-chevron-down"></i></Link>
                            </div>
                            <ul>
                                <li> <Link href="webDesigning.html">Web Designing</Link> </li>
                                <li> <Link href="WebDevelopment.html">Web Development</Link> </li>
                                <li> <Link href="WebHosting.html">Web Hosting</Link> </li>
                                <li> <Link href="LogoDesigning.html">Logo Designing</Link> </li>
                                <li> <Link href="GraphicDesigning.html">Graphic Designing</Link> </li>
                                <li> <Link href="SecuritySystem.html">Security System</Link> </li>
                                <li> <Link href="DomainRegistration.html">Domain Registration</Link> </li>
                                <li> <Link href="Marketing360.html">Marketing 360</Link> </li>
                                <li> <Link href="videoanimation.html">Video Animation</Link> </li>
                            </ul>
                        </li>
                        <li className="list__item">

                            <div className="sideMenuinner flex_ flex_space">
                                <Link href="contact.html">Contact Us</Link>
                                <Link href="" className="dropdown"><i className="fa-solid fa-chevron-down"></i></Link>
                            </div>
                        </li>
                        <li className="list__item">
                            <div className="sideMenuinner flex_ flex_space">
                                <Link href="">Portfolio</Link>
                                <Link  href=""  className="dropdown"><i className="fa-solid fa-chevron-down"></i></Link>
                            </div>
                        </li>
                        <li className="list__item">

                            <div className="sideMenuinner flex_ flex_space">
                                <Link href="">RATING & REVIEWS</Link>
                                <Link href="" className="dropdown"><i className="fa-solid fa-chevron-down"></i></Link>
                            </div>
                        </li>
                    </ul>
                </nav>
                <Link href="packages.html" className="btn btn-secondary"><b>Packages</b>
                    <span style={{transitionDelay: ".3s"}}></span>
                    <span style={{transitionDelay: ".4s"}}></span>
                    <span style={{transitionDelay: ".5s"}}></span>
                    <span style={{transitionDelay: ".6s"}}></span></Link>
            </div>
        </div>
        <div className="header__side flex_ align_center flex_center">
            <div className="flex_ align_center flex_center">
                <Link href="/" className="company__name">
                    Fast Buddys
                </Link>
                <Link href="" className="company__scroll flex_ align_center flex_center">
                    <Image src={require('./dist/webImages/1.png')} alt="" />
                    <span>Scroll</span>
                    <span className="company__scroll--line"></span>
                </Link>
            </div>
        </div>
    </header>
        {children}
        </body>
    </html>
  )
}
